[package]
name = "interior-mutability"
version = "0.1.0"
authors = ["Tom Ward <tom@popdog.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
